ALTER TABLE tickets ADD COLUMN IF NOT EXISTS sla_type TEXT NOT NULL DEFAULT 'normal';
ALTER TABLE tickets ADD COLUMN IF NOT EXISTS sla_hours INTEGER NOT NULL DEFAULT 24;
ALTER TABLE tickets ADD COLUMN IF NOT EXISTS sla_deadline TIMESTAMPTZ;
